export { default as NavBar } from './navbar/Navbar'
export { default as Header } from './header/Header'
export { default as About } from './about/About'
export { default as Service } from './service/Service'
export { default as Edge } from './edge/Edge'
export { default as Clients } from './clients/Clients'